### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by m90att** [custom-cards/vertical-stack-in-card#69]
I followed the instructions to install and got this error, any ideas what the cause is please?

Fri Nov 08 2019 15:34:20 GMT+0000 (Greenwich Mean Time)
https://www.myurl.com/local/vertical-stack-in-card.js?v=0.1.3:7:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by ofekashery** [comment]
This is most likely because you downloaded the [html](https://github.com/custom-cards/vertical-stack-in-card/blob/master/vertical-stack-in-card.js) instead of the [raw](https://raw.githubusercontent.com/custom-cards/vertical-stack-in-card/master/vertical-stack-in-card.js). That is not valid javascript. Always make sure you download using raw button. After downloading the file again with the 'raw' button, remember to bump the version number for the custom component speficied in the 'resources' of your lovelace-ui.yaml file.

**Comment by m90att** [comment]
Thanks for this.  I saved the raw format, uploaded it to HA, changed the version to 0.1.4, restarted but I'm getting the same error.  I tried changing the version back but same error.  I'm feeling a bit silly for not knowing but when you are not familiar with something it's difficult to know what to do.  I've followed the instructions and it's not working.

**Comment by m90att** [comment]
I've sorted it.  it was the '-' and indentation in your example.  I removed the '-' and moved everything left 2 spaces and it's working.
